name: Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install Yarn for building
      - name: Install Yarn
        run: npm install yarn

      - name: Install dependencies
        run: yarn install

      # Build form.js
      - name: Build form.js with Webpack
        run: yarn build

